---

- name: install common apt packages
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
    cache_valid_time: "{{ common_cache_valid_time | default(3600) }}"
  with_items:
    - htop
    - python-pip
    - git
    - vim
    - unzip
