
- name: add mongo repo key
  apt_key:
    keyserver: "hkp://keyserver.ubuntu.com:80"
    id: 7F0CEB10

- name: add mongo repo
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/ubuntu {{ansible_lsb.codename}}/mongodb-org/3.0 multiverse"
    update_cache: yes

- name: install mongodb
  apt:
    name: "mongodb-org"
    state: present

