# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "postgres"
    vb.memory = 1024
    vb.cpus = 2
  end

  config.vm.provision "ansible" do |an|
    an.playbook = "playbook.yml"
    an.sudo = true
  end
end
