---
- name: add docker repo key
  apt_key:
    keyserver: "hkp://keyserver.ubuntu.com:80"
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: add docker repo
  apt_repository:
    repo: "deb https://get.docker.com/ubuntu docker main"
    update_cache: yes

- name: install docker
  apt:
    name: lxc-docker
    state: present


- name: configure docker daemon options
  template:
    src: docker.j2
    dest: /etc/default/docker
  notify:
    - restart docker

- meta: flush_handlers  
# Since the Ansible Docker module will probably be used
# later, might as well install docker-py, as it's required
- name: install docker-py
  pip:
    name: docker-py


- name: add docker users
  user:
    name: "{{ item }}"
    append: yes
    groups: docker
  with_items: docker_users
