

- name: copy the incident response configuration
  template:
    src: incres.yml.j2
    dest: /usr/local/etc/incres.yml

    #TODO: handler for configuration changes



- name: install incident response firewall nat built
  docker:
    command: "incres {{ incres_options }} -c /incres.yml nat-built"
    insecure_registry: yes
    image: "{{ incres_docker_image }}"
    pull: always
    name: "incres_nat_built"
    state: reloaded
    restart_policy: always
    dns: "{{ incres_dns | default(omit) }}"
    net: "host"
    volumes:
      - "/usr/local/etc/incres.yml:/incres.yml"
      - "{{ incres_logs_fw_dir }}:/logs/firewall"
  when: incres_nat_built


- name: install incident response firewall nat teardown
  docker:
    command: "incres {{ incres_options }} -c /incres.yml nat-teardown"
    insecure_registry: yes
    image: "{{ incres_docker_image }}"
    pull: always
    name: "incres_nat_teardown"
    state: reloaded
    restart_policy: always
    dns: "{{ incres_dns | default(omit) }}"
    net: "host"
    volumes:
      - "/usr/local/etc/incres.yml:/incres.yml"
      - "{{ incres_logs_fw_dir }}:/logs/firewall"
  when: incres_nat_teardown


- name: install incident response dhcp
  docker:
    command: "incres {{ incres_options }} -c /incres.yml dhcp-ack"
    insecure_registry: yes
    image: "{{ incres_docker_image }}"
    pull: always
    name: "incres_dhcp_ack"
    state: reloaded
    restart_policy: always
    dns: "{{ incres_dns | default(omit) }}"
    net: "host"
    volumes:
      - "/usr/local/etc/incres.yml:/incres.yml"
      - "{{ incres_logs_dhcp_dir}}:/logs/dhcp"
  when: incres_dhcp



- name: install incident response web
  docker:
    command: "incres {{ incres_web_options }} -c /incres.yml web"
    insecure_registry: yes
    image: "{{ incres_docker_image }}"
    pull: always
    name: "incres_web"
    state: reloaded
    restart_policy: always
    dns: "{{ incres_dns | default(omit) }}"
    net: "host"
    expose:
      - "{{ incres_web_port }}"
    volumes:
      - "/usr/local/etc/incres.yml:/incres.yml"
  when: incres_web


- name: install incident response arp
  docker:
    command: "incres {{ incres_options }} -c /incres.yml arp"
    insecure_registry: yes
    image: "{{ incres_docker_image }}"
    pull: always
    name: "incres_arp"
    state: reloaded
    restart_policy: always
    dns: "{{ incres_dns | default(omit) }}"
    net: "host"
    volumes:
      - "/usr/local/etc/incres.yml:/incres.yml"
      - "{{ incres_logs_arp_dir }}:/logs/arp"
  when: incres_arp
